### ISSUE TITLE
Improve the messaging in the history table

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#54]
At the moment the history table displays the same error message "Waiting for files to be uploaded by the user" for every upload that has failed. The getHistory endpoint returns the upload status code for each attempted upload so we should be able to display a more informative error message about where the upload failed in the process.

**Comment by jamiehewitt15** [comment]
This could be caused by the status codes not being stored correctly in the database. We should first test if the DB is storing the right codes

**Comment by EnzoVezzaro** [comment]
For what I can see, when an user makes a quote, but it doesn't upload the file, he'll get a "Waiting for files to be uploaded by the user" message because the server is returning `status: 1` on this file. Can you screenshot the status code of the failing upload? it should give you the correct message if the code is correct.

<img width="1420" alt="Screenshot 2023-10-03 at 11 48 14 AM" src="https://github.com/oceanprotocol/uploader-ui-lib/assets/13741335/026122a5-f4d7-4a91-93e7-c716e72efaa8">
<img width="529" alt="Screenshot 2023-10-03 at 11 48 47 AM" src="https://github.com/oceanprotocol/uploader-ui-lib/assets/13741335/084a2648-229f-4b05-be81-6b676898c199">

**Comment by jamiehewitt15** [comment]
> For what I can see, when an user makes a quote, but it doesn't upload the file, he'll get a "Waiting for files to be uploaded by the user" message because the server is returning status: 1 on this file.

Yeah that's correct, no problem there. The issue that we need to address here is that if the file upload fails due to a payment failure `200-299` it still shows the  "Waiting for files to be uploaded by the user" message - instead it should show a message that says something like "payment failed". This is the problem that @AnaLoznianu  reported on slack

**Comment by EnzoVezzaro** [comment]
the problem here is that when anything fails from the wallet (allowance or payment for example), we get an error 500 with a long text in the data object like this one: `"Error uploading to micro-service: Error occurred while making the request: 400 Client Error: Bad Request for url: http://uploader-arweave.uploader-test.svc.cluster.local:8081/upload/?quoteId=7fd25e4732d7c74106b637a617d32d2d&nonce=1696418090&signature=0x109d13644b75247cc69c7e0e80f520ca6f2481eef1ce22b032fe5602df9e0e2d5ebfca4b75d36cb2901ea10d853008edd0c1df5146475c34e55882f52f28c5291c. Detailed message: {"message":"Allowance is less than current rate. Quoted amount: 885158092893709, current rate: 328432842880569, allowance: 0"}"`, that's why we're showing a generic "Upload failed!" as error message. But if we want to show a more meaningful message on the ui, we need to change the backend to return the exact message to show. 

Can we change it to return just what's inside "Detailed message"? @jamiehewitt15 

This way we can give the user a better error message on the input, but this doesn't solve anything on the history endpoint. To solve this, we need to catch the error and update the status code on the record we're trying to pay.

**Comment by jamiehewitt15** [comment]
> I haven't been able to replicate this. Do you know the exact steps to reproduce this error?

Yeah, these are the steps:
1. Connect with a wallet that has zero WMATIC in it
2. Request a Quote
3. Click Upload
4. It will fail with a payment error. 
5. Request history and the status message for the failed upload is "Waiting for the file to be uploaded by the user" 

A couple of thoughts on this: 
1. I think this issue is actually low priority as it soon won't be possible to attempt an upload without WMATIC in the wallet, so nobody will actually follow the steps above. 
2. The actual error here could be on the backend not storing or sending the correct status. 

> Can we change it to return just what's inside "Detailed message"? @jamiehewitt15
Yeah, we should do that so that you can give the user immediate feedback. That's not exactly related to the history table though, the get History endpoint should return the error codes that you need for this table.

**Comment by jamiehewitt15** [comment]
Another thought on this... If the user hasn't uploaded the files, does it really need to be in this table?

**Comment by EnzoVezzaro** [comment]
> A couple of thoughts on this:
> 
> 1. I think this issue is actually low priority as it soon won't be possible to attempt an upload without WMATIC in the wallet, so nobody will actually follow the steps above.
> 2. The actual error here could be on the backend not storing or sending the correct status.

Agree on both points. Once the upload button is disabled based on the user's balance, then he shouldn't get this error anymore. 

> Another thought on this... If the user hasn't uploaded the files, does it really need to be in this table? It might be clearer if this table is just for upload history, rather than the history of every quote.

yes, I don't think is necessary to show these records to the user. We can exclude them from the response, right?

**Comment by jamiehewitt15** [comment]
I also think showing the status code number makes this table more confusing... Showing a 200 status code for a failed upload seems confusing to me. Maybe we should remove the code numbers from this?

**Comment by EnzoVezzaro** [comment]
> I also think showing the status code number makes this table more confusing... Showing a 200 status code for a failed upload seems confusing to me. Maybe we should remove the code numbers from this?

Agree. Let's do that 👍🏽

**Comment by EnzoVezzaro** [comment]
Hi @jamiehewitt15 what are we missing from this PR? we just need filter the result to remove the status: 1 records from the history list response, right? or is there something else?

**Comment by EnzoVezzaro** [comment]
Status code "1" has been removed in [this PR](https://github.com/oceanprotocol/uploader_arweave/pull/65)

**Comment by jamiehewitt15** [comment]
Cool, thanks for this Enzo. Let's deploy the fix in prod and test it
